<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
        <Platforms>x64;x86</Platforms>
        <UseWindowsForms>true</UseWindowsForms>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <UseWPF>true</UseWPF>
        <LangVersion>12</LangVersion>
        <Nullable>disable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Configurations>Debug;Release;Debug-NAudio;Release-NAudio</Configurations>
    </PropertyGroup>

    <PropertyGroup>
        <Product>Emuera</Product>
        <RootNamespace>MinorShift.Emuera</RootNamespace>
        <ApplicationManifest>emuera.manifest</ApplicationManifest>
        <Version>2.4</Version>
        <InformationalVersion>1.824+v21+EMv18+EEv47 LazyLoadingv2.4</InformationalVersion>
        <Copyright>Copyright (C) 2008- MinorShift, 妊）|дﾟ)の中の人</Copyright>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>

    <PropertyGroup>
        <IncludeAllContentForSelfExtract>false</IncludeAllContentForSelfExtract>
        <SelfContained>false</SelfContained>
        <PublishReadyToRun>false</PublishReadyToRun>
        <PublishSingleFile>true</PublishSingleFile>
        <PublishTrimmed>false</PublishTrimmed>
        <SelfContained>false</SelfContained>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <AssemblyName>LazyLoadingV2</AssemblyName>
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
        <DefineConstants>DEBUG</DefineConstants>
        <DebugSymbols>true</DebugSymbols>
        <Optimize>false</Optimize>
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration.Contains('Release'))">
        <Optimize>true</Optimize>
        <DebugSymbols>False</DebugSymbols>
        <DebugType>None</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="$(Configuration.Contains('NAudio'))">
        <DefineConstants>NAudio</DefineConstants>
        <InformationalVersion>$(InformationalVersion) NAudio</InformationalVersion>
        <AssemblyName>$(AssemblyName)-NAudio</AssemblyName>
    </PropertyGroup>

    <ItemGroup Condition="!($(Configuration.Contains('NAudio')))">
        <Compile Remove="_Library\Sound.NAudio.cs" />
        <Compile Remove="_Library\NAudio_LoopStream.cs" />
    </ItemGroup>

    <ItemGroup Condition="$(Configuration.Contains('NAudio'))">
        <PackageReference Include="NAudio.Core" Version="2.2.1" />
        <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
        <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
    </ItemGroup>
    <PropertyGroup>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>

    <ItemGroup Condition="$(RuntimeIdentifier.Equals('win-x64')) Or '$(Platform)' == 'x64'">
        <None Update="Libs\Webp\x86_64\libsharpyuv.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>libsharpyuv.dll</TargetPath>
        </None>
        <None Include="Libs\Webp\x86_64\libwebp.dll">
            <TargetPath>libwebp.dll</TargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup Condition="$(RuntimeIdentifier.Equals('win-x86')) Or '$(Platform)' == 'x86'">
        <None Update="Libs\Webp\x86\libsharpyuv.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <TargetPath>libsharpyuv.dll</TargetPath>
        </None>
        <None Update="Libs\Webp\x86\libwebp_x86.dll">
            <TargetPath>libwebp_x86.dll</TargetPath>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Properties\lang\emuera-eng.xml" />
      <EmbeddedResource Include="Properties\lang\emuera-zhs.xml" />
      <EmbeddedResource Include="Properties\fonts\BIZUDGothic-Regular.ttf" />
    </ItemGroup>
</Project>